spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        type: trace

darksky:
  url: 'https://api.darksky.net/forecast/'
  key: 'aa1321e9abac62c00bd7c75d5d5e83f8'
#todo usunac key
